Trn 17 php assignment image
Ankush-1001/AssignmentsInnoraft pull request #2
Opened 2021-03-16 07:24 UTC by Ankush-1001

Pull request for code review

2021-03-17 08:35 UTC, arjak-dev requested changes

2021-03-17 08:35 UTC, arjak-dev commented on Assignment2/action.php
> +      //print_r($file);
Remove this line.

2021-03-17 08:35 UTC, arjak-dev commented on Assignment2/action.php
> +      //print_r($path_filename_ext);
remove this line

2021-03-17 08:35 UTC, arjak-dev commented on Assignment2/index.php
> +      echo $file;
what is the use of this $file?

2021-03-17 08:35 UTC, arjak-dev commented on Assignment2/index.php
> +  <?php  //output of code
Can we do this checking in the php file.

2021-03-17 14:02 UTC, Ankush-1001 reviewed
Yes we can do the checking in php file but just for output purpose I put these conditions here in html file so that correct msg will get displayed.

$file is used as it contain the name of the image file so to display the image file $file is used for  echo.

2021-03-18 04:37 UTC, Ankush-1001 commented on Assignment2/index.php
> +      echo $file;
hello

2021-03-18 07:35 UTC, Ankush-1001 commented on Assignment2/index.php
> +  <?php  //output of code
Yes we can do the checking in php file but just for output purpose I put these conditions here in html file so that correct msg will get displayed.

2021-03-18 07:35 UTC, Ankush-1001 commented on Assignment2/index.php
> +      echo $file;
$file is used as it contain the name of the image file so to display the image file $file is used for echo.

2021-03-18 09:00 UTC, arjak-dev requested changes

2021-03-18 09:04 UTC, Ankush-1001 commented on Assignment2/index.php
> +      echo '<img src='.$path_filename_ext.' height=200 width=300 />';
$fileupload is a variable that stores a message that file is uploaded successfully.
and <img src> is used for displaying the image if uploaded sucessfully.

2021-03-18 09:18 UTC, merged